### ISSUE TITLE
NullPointerException when setting font

### ISSUE THREAD

**Issue by fedeb95** [madlitch/MadPixelSort#1]
When running from Processing, it gives this error
![Screenshot from 2021-03-12 12-26-50](https://user-images.githubusercontent.com/25415908/110934473-59027680-832e-11eb-84ae-4b193266d124.png)

**Comment by fedeb95** [comment]
ok solved by manually specifing font path. Maybe there's a better way, and also include this in the documentation?

**Comment by madlitch** [comment]
Was the .pde file moved from the directory it came in? Or did you just run the .pde directly

**Comment by fedeb95** [comment]
I run the pde directly

**Comment by pixelnull** [comment]
> ok solved by manually specifing font path. Maybe there's a better way, and also include this in the documentation?

Can you tell me how you did this?
